### ISSUE TITLE
Ethernet Shield

### ISSUE THREAD

**Issue by mnoeth93** [miguelbalboa/rfid#21]
Hi,

your library is great and works like charm! But I experienced some issues when connecting an Ethernet shield to my arduino due. After some googling I found out that the Ethernet shield has a flaw. If I put the Ethernet shields chip select to low the shield is still sending an receiving data from the MISO/MOSI ports. 

Do you know any fix for that or can you say me if the design flaw of the newer versions of the ethernet shield still exists?

**Comment by rctl** [comment]
@mnoeth93 
Hi,
I have the exact same issue that you are experiencing. Even bought a new Ethernet shield because I thought that I have fried my first one before I found this thread. I am using an unshielded cable of like 10-15 m, so pretty long. My pin mapping for the RFID chip is:

SS -> Pin 46 (Changed this from 52 as this was configurable)
SCK -> Pin 53 (This one is interfering, ethernet works with it disconnected)

RFID works fine but the Ethernet is acting up (showing ip addresses like 0.0.0.0, 1.1.0.0 etc).

So I took your advice and applied resistors between SCK and GND on both ends, on 4.7k Ohm, what values did you use on your resistors? Mine seems to still have interferrance and I really want to avoid having to change to a shielded cable.
