### ISSUE TITLE
A humble request to anyone who can rewrite MFRC522 library to use UART imterface

### ISSUE THREAD

**Issue by cyberjupiter** [miguelbalboa/rfid#281]
Hi. I am not a skilled nor an experienced programmer. Even after looking at the datasheet, changing the current SPI interface to UART is totally beyond my level.

Therefore, I really hope someone will implement the MFRC522 library which uses UARt interface.

**Comment by Rotzbua** [comment]
Maybe this user did it #221 
duplicate #257

**Comment by cyberjuputer** [comment]
Is there any way to contact him? I am new to github and it seems to not have PM function.

Anyway, I will try to figure out what he did from his comments. There is so little information from his comments but I will give it a shot.

**Comment by Dizgah** [comment]
As I remember ,Framing in SPI is different with UART in MFRC522,datasheet completely described framing for each connection.Please read datasheet and if your problem does not resolved contact me via MHDizgah@gmail.com

**Comment by cyberjuputer** [comment]
Hi @Dizgah 

Yes, I have read the datasheet and I can differentiate how data is sent between SPI and UART. However, I do not know how to implement it. As I have stated in my first post, my knowledge in programming is limited. If you have some examples that I could follow through, that would be helpful. 

P/S: The problem is that the MFRC522 library uses SPI entirely. How do I modify which lines to use UART? And as far as I know, UART is a serial communication and in Arduino, there is no library for UART. You just use it. Thats why I am very confused.

**Comment by omersiar** [comment]
This Library:

https://github.com/zodier/MFRC522-UART-Arduino

**Comment by Rotzbua** [comment]
Any update

**Comment by davidjonz2005** [comment]
https://github.com/davidjonz2005/MFRC522WITHUART
