### ISSUE TITLE
IDE is prompting to update to an _older_ version?

### ISSUE THREAD

**Issue by DrLou** [miguelbalboa/rfid#300]
### Step 1: Are you in the right place?
Geesh, I hope so!

### Step 2: Describe your environment
OSX - arduino IDE

### Step 3: Describe the problem
not much of a problem - but the IDE occasionally reports _Library updates available_ (or similar), but then offers an older version as the update. 

For example, having _just now_ installed your great update 1.3.3 - the IDE Library Manager reports I have 1.1.9 installed, and offers to 'Update' - to no version higher than 1.3.2!

Do I have a problem with my original install - or integration - of the RFID libs?

I am keen to stay fully _up-to-date_ with latest HEAD of work...

**Comment by Rotzbua** [comment]
Hi, thanks for your report. Did you install 1.3.3 manually?

**Comment by Rotzbua** [comment]
The arduino ide do not crawl the actual versions from github. Instead there is a global index file at arduino.cc where they daily crawl all repositories. This means it can be possible that you manually install 1.3.3 and your IDE knows only about version 1.3.2.

If you have this library installed and shows correctly 1.3.3 and select the entry in the library manager, the dropdown shows 1.3.2 and lower because you can downgrade to an older version.

So if it shows 1.3.3. as current version, everything is fine.

**Comment by DrLou** [comment]
It doesn't (show 1.3.3) as the current version...  with 1.3.3 installed, it shows 1.1.9 as the 'current' version.

In this state, the dropdown list shows all versions _except_ 1.3.3 (installed) and 1.1.9.

I happen to be looking at this as we speak. I'll see if I can sort it out.

**Comment by Rotzbua** [comment]
Ok, then I close this :+1: 
The PN532? There are a lot of useful libraries (adafruit,seeedstudio) already available. So no plans.
