### ISSUE TITLE
MifareClassicValueBlock default values

### ISSUE THREAD

**Issue by ep2610** [miguelbalboa/rfid#343]
Is it possible to revert changes made by MifareClassicValueBlock ?
Meaning blocks 5,6,7 and access bits to restore to factory default settings ?

**Comment by Rotzbua** [comment]
Hi, thanks for your message.
Your report do not satisfy the requirements of a good issue report.  Please provide basic information by the issue template https://github.com/miguelbalboa/rfid/blob/master/.github/ISSUE_TEMPLATE.md . The template helps other people to understand your situation and according problems.
This issue is closed. Please reopen a new issue report which satisfy all requirements of a good issue report. Kind regards.
