### ISSUE TITLE
How to pass a function from the RFID-RC522 into a variable then be sent into either serial or ethernet?

### ISSUE THREAD

**Issue by saiyojeff** [miguelbalboa/rfid#63]
I'm using an RC522 RFID reader with an Arduino UNO. There is a function?? (or whatever it's called :)) in Miguel Balboa's new MFRC522.h library which is mfrc522.uid.uidByte[i] that prints the bytes of the unique ID. The repetition of the function results in 8 piece of HEX digits that are from the 2 numbers that each function outputs (2+2+2+2=8). Whenever I use the line of codes that are commented out, the serial monitor outputs them successfully. So for example, 12345678 is the unique id, each array displayed 12, then 34, then, 56, then 78 which is 12345678 in the serial. which is fast and unnoticeable besides that there are no spaces included when on output. The thing is, I want to output all of these into a single variable.(Please help me also on how to concatenate) How can I do this? An attempt was done below (not commented out) but it outputs only the number 16, consistently, which is I think due to a data type problem. The variables are initialized as int. The "function" which I found in the library is initialized as byte (correct me If I'm wrong). But when the variables are initialized as byte, I cannot upload the sketch since there are errors. Please help. :( (The reason I need it to be saved into a single variable is because I am placing it in the GET method of an Ethernet Client. I don't think the bare function can do that. (Or if it can, can you please help with the code? :)) Thanks

**Comment by Ouss99** [comment]
i use this library and i have a problem
'class MFRC522' has no member named 'PCD_INT'
i need helpppp

**Comment by mdxs** [comment]
From what I understand: @saiyojeff and @gaelperon solved their particular issues and this issue could be closed.

@Ouss99 should raise a different issue/ticket instead of commenting here.

**Comment by ibnumuhammad** [comment]
that's work on arduino ?!?!?!

**Comment by azizmasr93** [comment]
@gaelperon "'StringAdd' was not declared in this scope " what a data type ?

**Comment by Jman9832** [comment]
I can't seem to make it so that when a specific UID is passed through it will print a message


/*
 * MFRC522 - Library to use ARDUINO RFID MODULE KIT 13.56 MHZ WITH TAGS SPI W AND R BY COOQROBOT.
 * The library file MFRC522.h has a wealth of useful info. Please read it.
 * The functions are documented in MFRC522.cpp.
 *
 * Based on code Dr.Leong   ( WWW.B2CQSHOP.COM )
 * Created by Miguel Balboa (circuitito.com), Jan, 2012.
 * Rewritten by Søren Thing Andersen (access.thing.dk), fall of 2013 (Translation to English, refactored, comments, anti collision, cascade levels.)
 * Released into the public domain.
 *
 * Sample program showing how to read data from a PICC using a MFRC522 reader on the Arduino SPI interface.
 *----------------------------------------------------------------------------- empty_skull 
 * Aggiunti pin per arduino Mega
 * add pin configuration for arduino mega
 * http://mac86project.altervista.org/
 ----------------------------------------------------------------------------- Nicola Coppola
 * Pin layout should be as follows:
 * Signal     Pin              Pin               Pin
 *            Arduino Uno      Arduino Mega      MFRC522 board
 * ------------------------------------------------------------
 * Reset      9                5                 RST
 * SPI SS     10               53                SDA
 * SPI MOSI   11               51                MOSI
 * SPI MISO   12               50                MISO
 * SPI SCK    13               52                SCK
 *
 * The reader can be found on eBay for around 5 dollars. Search for "mf-rc522" on ebay.com. 
 */

#include <SPI.h>
#include <MFRC522.h>

#define SS_PIN 10
#define RST_PIN 9
MFRC522 mfrc522(SS_PIN, RST_PIN);   // Create MFRC522 instance.

int grantedUID = "7C 1F 2E 5B";

void setup() {
    Serial.begin(230400); // Initialize serial communications with the PC
    SPI.begin();            // Init SPI bus
    mfrc522.PCD_Init(); // Init MFRC522 card
    Serial.println("Scan PICC to see UID and type...");
}

void loop() {
    // Look for new cards
    if ( ! mfrc522.PICC_IsNewCardPresent()) {
        return;
    }

    // Select one of the cards
    if ( ! mfrc522.PICC_ReadCardSerial()) {
        return;
    }


    // Dump debug info about the card. PICC_HaltA() is automatically called.
    mfrc522.PICC_DumpToSerial(&(mfrc522.uid));

    Serial.print("UID size : ");
    Serial.println(mfrc522.uid.size);

 Serial.print("Printing HEX UID : ");
  for (byte i = 0; i < mfrc522.uid.size; i++) {
    Serial.print(mfrc522.uid.uidByte[i] < 0x10 ? " 0" : " ");
    Serial.print(mfrc522.uid.uidByte[i], HEX);
  } 
  Serial.println("");

  unsigned long UID_unsigned;
  UID_unsigned =  mfrc522.uid.uidByte[0] << 24;
  UID_unsigned += mfrc522.uid.uidByte[1] << 16;
  UID_unsigned += mfrc522.uid.uidByte[2] <<  8;
  UID_unsigned += mfrc522.uid.uidByte[3];

  Serial.println();
  Serial.println("UID Unsigned int"); 
  Serial.println(UID_unsigned);

  String UID_string =  (String)UID_unsigned;
  long UID_LONG=(long)UID_unsigned;

  Serial.println("UID Long :");
  Serial.println(UID_LONG);

  Serial.println("UID String :");
  Serial.println(UID_string);

if(mfrc522.uid.uidByte == grantedUID) {
   Serial.println("access granted");
}


  
}

**Comment by fihircio** [comment]
send uid tags only when tagged to GET query pushingbox parse to gsheet. added weigand uhf data tags for uhf reader. parameter for parse to gsheet new column for 2nd sensor(uhf/passive) still work in progress.
references :- 
http://shahrulnizam.com/ct-uno-lesson-wiegand-rfid-reader/
https://www.youtube.com/watch?v=fVBqUeksR1I


int count=0;
unsigned int rfid=0;

#include <SPI.h>
//#include <RFID.h>
#include <MFRC522.h>
#include <Ethernet.h>


void make_request(String& id);                                     // make a badge request
//-------------------------------------------------------------------------------

byte mac[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED }; //Setting MAC Address

char server[] = "api.pushingbox.com"; //pushingbox API server

IPAddress ip(192,168,1,2); //Arduino IP address. Only used when DHCP is turned off.

EthernetClient client; //define 'client' as object

String data; //GET query with data

float uhf; 

float passive; 

boolean koneksi = false;

    // CONFIG RFID
#define SS_PIN 4
#define RST_PIN 8
MFRC522 mfrc522(SS_PIN, RST_PIN);  

unsigned long previousMillis = 0, currentMillis = 0;


//------------------------------------------------------------------------------

void setup() {

  Serial.begin(9600);
  pinMode(2, INPUT_PULLUP);
  pinMode(3, INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(2), data0, FALLING);
  attachInterrupt(digitalPinToInterrupt(3), data1, FALLING);


  if (Ethernet.begin(mac) == 0) {

	Serial.println("Failed to configure Ethernet using DHCP");

	Ethernet.begin(mac, ip);

  }

  delay(1000);
  
    SPI.begin(); 
    // mfrc522.init();
     mfrc522.PCD_Init(); // Init MFRC522 card
  Serial.println(F("Device setup.."));
     
//         // disable rfid
//     pinMode(8, OUTPUT);
//     digitalWrite(8, HIGH);

}

//------------------------------------------------------------------------------

void loop(){

 
  
  if ( ! mfrc522.PICC_IsNewCardPresent()) {
// delay(1500); 
// mfrc522.PCD_DumpVersionToSerial(); 
 return;
 }
 
 if ( ! mfrc522.PICC_ReadCardSerial()) {
 return;
 }
 
  
  
  Serial.println("");
  
  
//-------------------------------------
  
  

  if((count>=26)&&(rfid!=0))
  {
  rfid=rfid>>1;
    Serial.print("RFID Tag: ");
    Serial.println(rfid,DEC);
    count=0;
    //rfid=0;
    return;
  }
  
  //-------------------------------------
  
  uhf = rfid; // send database

 // passive = UID_unsigned; // send database

   kemasData(); //packing GET query with data

   Serial.println("connecting...");

   if (client.connect(server, 80)) {

     sendData();  

     koneksi = true; //connected = true
     
     //-------------------------------------
     
     
      char c = client.read(); //save http header to c

	  Serial.print(c); //print http header to serial monitor

     //-------------------------------------

          Serial.println(uhf); //print sent value to serial monitor

          Serial.println(passive); //print sent value to serial monitor
          
	  client.stop(); 

         koneksi = false; 

         data = ""; //data reset
   
     //-------------------------------------
 
 }

   else{

     Serial.println("connection failed");

   }

  // loop

/*  while(koneksi){

    if (client.available()) {

	  char c = client.read(); //save http header to c

	  Serial.print(c); //print http header to serial monitor

    }

    if (!client.connected()) {

	  Serial.println();

	  Serial.println("disconnecting.");

          Serial.print("RFID Sent :");

          Serial.println(suhu); //print sent value to serial monitor

	  client.stop(); 

          koneksi = false; 

          data = ""; //data reset

    }

  } */

  delay(5000); // interval

}

//-------------------------------------

void kemasData(){

  data+="";

  data+="GET /pushingbox?devid=???&tempData="; //GET request query to pushingbox API


  data+=uhf;
  //data+=passive;
 
  data+=" HTTP/1.1";

}

//-------------------------------------

void sendData(){

  Serial.println("connected");

  client.println(data);

  client.println("Host: api.pushingbox.com");

  client.println("Connection: close");

  client.println();

}

//-------------------------------------

void data0()
{
  rfid=(rfid<<1);
  count++;
}

void data1()
{
  rfid=(rfid<<1)|1;
  count++;
}
